[project]
name = "typetype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elevate>=0.1.3",
    "evdev>=1.9.2",
    "httpx>=0.28.1",
    "pycryptodome>=3.23.0",
    "pyside6>=6.10.1",
    "qasync>=0.28.0",
]

[tool.pyside6-project]
files = [
    "main.py",
    "qml/Main.qml",
    "src/backend/Crypt.py",
    "src/backend/GetSaiWen.py",
    "src/backend/text_properties.py",
    # 如果还有其他 Python 源文件，可以继续往上加，比如：
    # "window.py",
    # "model.py",
]
